apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: minimal-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      # nodeName: petshopboys
      containers:
        - name: payment
          image: ghcr.io/computernetworks-ufrgs/minimal-boutique-payment
          ports:
            - containerPort: 5004
          env:
            - name: OTLP_ENDPOINT
              value: "http://collector.mcp-hub.svc.cluster.local:4321/v1/traces"

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: minimal-boutique
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP
