apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: ghcr.io/computernetworks-ufrgs/minimal-boutique-products:latest
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_APP
          value: app
        - name: FLASK_ENV
          value: production
        command: ["gunicorn","--workers","4","--bind","0.0.0.0:5001","app:app"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
